const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const readers=require('../project-files.js');
const importer=require('../project-import.js');
const fflate=require('../vendor/fflate-0.8.3.js');
assert.equal(readers.fileType({name:'Plan.PDF',size:20}).mime,'application/pdf');
assert.equal(readers.fileType({name:'Plan.docx',size:20}).ext,'docx');
assert.throws(()=>readers.fileType({name:'plan.doc',size:20}),/Older .doc/);
assert.throws(()=>readers.fileType({name:'plan.exe',size:20}),/Choose/);
assert.throws(()=>readers.fileType({name:'plan.pdf',size:readers.MAX_SIZE+1}),/10 MB/);
const zip=fflate.zipSync({'word/document.xml':new TextEncoder().encode('<document/>'),'unrelated.txt':new Uint8Array(100)});
const Parser=class {parseFromString(xml){assert.equal(xml,'<document/>');return {getElementsByTagName:()=>[],getElementsByTagNameNS:()=>[{getElementsByTagNameNS:()=>[{textContent:'Shelf 24 inches'}]}]};}};
assert.equal(readers.docxText(zip,fflate.unzipSync,Parser),'Shelf 24 inches');
assert.throws(()=>readers.docxText(fflate.zipSync({'other.xml':new Uint8Array(1)}),fflate.unzipSync,Parser),/not a readable Word/);
assert.throws(()=>readers.docxText(new Uint8Array(2),(_b,opts)=>{opts.filter({name:'word/document.xml',originalSize:5000000});},Parser),/too large/);
const plan={projectName:'Shelf',summary:'24 inches',budget:40,projectTasks:[{title:'Install'}],materials:[{item:'Board',quantity:'1'}],cutList:[{piece:'Board',dimensions:'24 inches'}],buildSteps:[{title:'Install',instructions:'Use brackets'}],toolsNeeded:[{tool:'Drill'}]};
assert.equal(importer.parseProject(readers.planExport(plan)).budget,40);
const html=fs.readFileSync(require.resolve('../index.html'),'utf8');
const script=html.split('<script>',2)[1].split('</script>',1)[0];
const storage=script.slice(script.indexOf('function serializeStoredData('),script.indexOf('function loadData('));
const storageContext=vm.createContext({JSON,Map,STORED_IMAGE_PREFIX:'ref:',STORED_IMAGE_POOL:'pool',LOCAL_IMAGE_PREFIX:'local:',localImageUris:new Map()});
vm.runInContext(storage,storageContext);
for(const mime of ['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','text/plain','text/markdown','text/csv','application/json','image/jpeg']){
  const uri=`data:${mime};base64,AAAA`;
  const snapshot={projects:[{attachments:[{uri}]}]};
  const compact=storageContext.serializeStoredData(snapshot);
  assert.equal(JSON.parse(compact).projects[0].attachments[0].uri,'ref:0');
  assert.equal(storageContext.parseStoredData(compact).projects[0].attachments[0].uri,uri);
  storageContext.localImageUris.set('id',uri);
  assert.equal(storageContext.parseStoredData(JSON.stringify({pool:{0:'local:id'},projects:[{attachments:[{uri:'ref:0'}]}]})).projects[0].attachments[0].uri,uri);
}
const fields={};
for(const id of ['fileReaderStatus','fileReaderInput','fileReaderText','fileReaderImages','fileReaderBuild','fileReaderDialog','projectFileStatus'])fields[id]={value:'',innerHTML:'',textContent:'',hidden:false,disabled:false,addEventListener(){},querySelectorAll(){return [fields.fileReaderBuild];},showModal(){},close(){}};
const original={projects:[{id:'shelf',name:'Shelf'}],tools:[],home:{}};
let fail=true,writes=0,staged=null;
class Reader{readAsDataURL(blob){blob.arrayBuffer().then(buffer=>{this.result=`data:${blob.type};base64,${Buffer.from(buffer).toString('base64')}`;this.onload();});}}
const context=vm.createContext({document:{getElementById:id=>fields[id]},TextEncoder,TextDecoder,FileReader:Reader,Blob,File,Date,JSON,Number,String,Array,RegExp,Error,Uint8Array,crypto:{randomUUID:()=> 'id'},data:original,escapeHTML:s=>String(s??'').replaceAll('<','&lt;'),escapeAttribute:s=>String(s),persistLocalSnapshot:async()=>{if(fail)throw Error('disk full');writes++;},openProject(){},confirm:()=>true,queueCloudSync(){},photoToJpeg:async()=> 'data:image/jpeg;base64,BBBB',requestTheListAI:async payload=>{assert.match(payload.projectDescription,/24 inches/);return plan;},stageProjectFileImport:(raw,attachment)=>{staged={raw,attachment};}});
context.window=context;
vm.runInContext(fs.readFileSync(require.resolve('../project-files.js'),'utf8'),context);
(async()=>{
  const input={files:[new File(['Shelf 24 inches'],'plan.txt',{type:'text/plain'})],disabled:false,value:'plan.txt'};
  await context.attachProjectFiles('shelf',input);
  assert.equal(original.projects[0].attachments,undefined);
  assert.match(fields.projectFileStatus.textContent,/not added/);
  fail=false;await context.attachProjectFiles('shelf',input);
  assert.equal(writes,1);
  assert.equal(context.data.projects[0].attachments[0].mime,'text/plain');
  assert.equal(context.data.projects[0].attachments[0].uri,'data:text/plain;base64,U2hlbGYgMjQgaW5jaGVz');
  context.openFileProjectReader();
  await context.prepareProjectFile(input.files[0]);
  assert.equal(fields.fileReaderText.value,'Shelf 24 inches');
  await context.buildProjectFromFile();
  assert.equal(staged.attachment.name,'plan.txt');
  assert.equal(importer.parseProject(staged.raw).name,'Shelf');
  assert.match(importer.parseProject(staged.raw).notes,/Source text/);
  assert.equal(writes,1,'Reading and previewing do not save a project');
  assert.equal(context.data.projects.length,1);
  const syncSource=fs.readFileSync(require.resolve('../sync.js'),'utf8');
  const syncFunctions=syncSource.slice(syncSource.indexOf('  async function photoToPath('),syncSource.indexOf('  async function useCloud('));
  const buckets=[];
  const syncContext=vm.createContext({crypto:require('node:crypto').webcrypto,fetch,Blob,Uint8Array,Array,Object,String,JSON,Map,structuredClone,FileReader:Reader,household:{id:'family'},BUCKET:'the-list-photos',FILE_BUCKET:'the-list-files',PHOTO_PREFIX:'cloud:',uploaded:new Map(),downloaded:new Map(),STORED_IMAGE_POOL:'pool',serializeStoredData:storageContext.serializeStoredData,parseStoredData:storageContext.parseStoredData,client:{storage:{from:bucket=>({upload:async(path,blob)=>{buckets.push(bucket);assert.match(path,/^family\//);return {error:null};}})}}});
  vm.runInContext(`const fileBucket=path=>/\\.(pdf|docx|txt|md|csv|json)$/.test(path)?FILE_BUCKET:BUCKET;\n${syncFunctions}`,syncContext);
  const upload=await syncContext.cloudPayload({projects:[{attachments:[{uri:'data:application/pdf;base64,AAAA'}],roomPhotos:['data:image/jpeg;base64,BBBB']}]});
  assert.deepEqual(buckets,['the-list-files','the-list-photos']);
  assert.ok(Object.values(upload.pool).every(uri=>uri.startsWith('cloud:family/')));
  const restored=await syncContext.localPayload(upload);
  assert.equal(restored.projects[0].attachments[0].uri,'data:application/pdf;base64,AAAA');
  assert.equal(restored.projects[0].roomPhotos[0],'data:image/jpeg;base64,BBBB');
  console.log('File reading, storage failures, Sage previews and private household upload/download passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
