// Run with: node tests/project-import.test.js
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const importer=require('../project-import.js');
const fixture={format:'the-list-project',version:1,project:{name:'Five cubbies',description:'Five compartments, 80 inches wide',budget:325,notes:'Verify wall width',tasks:[{text:'Measure wall',dueDate:'2026-10-12'}],materials:[{name:'Plywood',quantity:'2 sheets',estimatedCost:120}],tools:['Drill'],cutList:[{piece:'Base',quantity:1,dimensions:'80 × 18 inches',material:'Plywood'}],buildSteps:[{title:'Measure',instructions:'Confirm the wall width',safety:'Check for wiring'}],measurementsNeeded:[{name:'Wall width',whyNeeded:'Fit'}],warnings:['Confirm dimensions before cutting']}};
const raw=JSON.stringify(fixture);
const parsed=importer.parseProject('```json\n'+raw+'\n```');
assert.equal(parsed.name,'Five cubbies');
assert.equal(parsed.materials[0].estimatedCost,120);
assert.equal(parsed.aiPlan.cutList[0].dimensions,'80 × 18 inches');
assert.equal(parsed.aiPlan.toolsNeeded[0].tool,'Drill');
assert.equal(parsed.tasks[0].dueDate,'2026-10-12');
assert.equal(parsed.tasks[0].done,false);
assert.equal(importer.parseProject(JSON.stringify({name:'Steps',buildSteps:fixture.project.buildSteps})).tasks[0].text,'Measure');
assert.throws(()=>importer.parseProject('plain text'),/not project JSON/);
assert.throws(()=>importer.parseProject(JSON.stringify({projects:[]})),/whole-app backup/);
assert.throws(()=>importer.parseProject(JSON.stringify({...fixture,version:2})),/unsupported/);
assert.throws(()=>importer.parseProject(JSON.stringify({name:'x',budget:-3})),/nonnegative/);
assert.throws(()=>importer.parseProject(JSON.stringify({name:'x',tasks:[{text:'Test',dueDate:'2026-02-30'}]})),/dates/);
assert.throws(()=>importer.parseProject(JSON.stringify({name:'x',tools:{}})),/arrays/);
assert.throws(()=>importer.parseProject(JSON.stringify({name:'x',materials:[{}]})),/material needs/);
assert.throws(()=>importer.parseProject(JSON.stringify({name:'x',tasks:Array(301).fill('x')})),/300/);
assert.throws(()=>importer.parseProject('x'.repeat(importer.MAX_BYTES+1)),/1 MB/);
assert.equal(importer.parseProject('{"name":"x","__proto__":{"polluted":true}}').polluted,undefined);
assert.match(importer.exportPrompt(),/the-list-project/);

const fields={};
for(const id of ['projectImportDialog','projectImportText','projectImportFile','projectImportPreview','projectImportSave','projectImportStatus','projectImportPrompt','projectImportBudget'])fields[id]={value:'',innerHTML:'',textContent:'',hidden:false,disabled:false,addEventListener(){},querySelectorAll(){return [fields.projectImportSave];},showModal(){this.open=true;},close(){this.open=false;},select(){}};
const original={projects:[{id:'existing',name:'Existing'}],tools:[{name:'Drill'}],shopping:[],aiChats:{}};
let fail=true,writes=0,syncs=0,opened='';
const context=vm.createContext({TextEncoder,Date,JSON,Math,Number,String,Array,Error,RegExp,crypto:{randomUUID:()=> 'new-id'},window:{queueCloudSync(){syncs++;}},document:{getElementById:id=>fields[id]},navigator:{clipboard:{writeText:async()=>{}}},data:original,escapeHTML:s=>String(s??'').replaceAll('<','&lt;').replaceAll('>','&gt;'),toolKey:s=>String(s).trim().toLowerCase(),persistLocalSnapshot:async next=>{if(fail)throw Error('disk full');writes++;assert.equal(next.projects.length,2);},setProjectFilter(){},openProject:id=>opened=id});
context.window=context;
context.queueCloudSync=()=>syncs++;
vm.runInContext(fs.readFileSync(require.resolve('../project-import.js'),'utf8'),context);
(async()=>{
  context.openProjectImport();
  fields.projectImportText.value=raw;
  context.previewProjectImport();
  assert.match(fields.projectImportPreview.innerHTML,/Have tool/);
  await context.saveImportedProject();
  assert.equal(context.data,original);
  assert.equal(original.projects.length,1);
  assert.equal(syncs,0);
  assert.match(fields.projectImportStatus.textContent,/not changed/);
  fail=false;
  await Promise.all([context.saveImportedProject(),context.saveImportedProject()]);
  assert.equal(writes,1);
  assert.equal(syncs,1);
  assert.equal(opened,'project-new-id');
  assert.equal(context.data.projects[0].id,'existing');
  assert.equal(context.data.projects[1].aiPlan.cutList.length,1);
  assert.equal(original.projects.length,1);
  context.openProjectImport();
  fields.projectImportText.value=JSON.stringify({name:'<img src=x onerror=alert(1)>'});
  context.previewProjectImport();
  assert.doesNotMatch(fields.projectImportPreview.innerHTML,/<img/);
  context.invalidateProjectImport();
  await context.saveImportedProject();
  assert.equal(writes,1);
  fields.projectImportText.value='invalid';context.previewProjectImport();
  assert.equal(fields.projectImportSave.hidden,true);
  console.log('Project imports preserve data on failure, save once, validate fields, and escape previews.');
})().catch(error=>{console.error(error);process.exitCode=1;});
